### ISSUE TITLE
Adding support for loading a gist from URL

### ISSUE THREAD

**Issue by wittekm** [ymyzk/mypy-playground#14]
Hi Yusuke!

I was thinking of adding a pull request that would allow the following behavior:

If you go to a URL like:
https://play-mypy.ymyzk.com/load_gist?gist_id=95b0767cf9890008ab88fbda4834eea7&py_version=27

which would then pre-populate the input box with the contents of https://gist.github.com/95b0767cf9890008ab88fbda4834eea7 and automatically set the python version to 2.7

This would make it easier to share your playground with other people!

---
Would you be interested in a pull request for this behavior?

**Comment by ymyzk** [comment]
@wittekm Thank you for proposing a new feature! 😄 And, I’m very happy if you make a PR.
I was considering to add a similar feature, but I have no time to work on this currently. 😢 

You proposal almost looks good for me. I prefer:

- Style of URL: https://play-mypy.ymyzk.com/?gist_id=95b0767cf9890008ab88fbda4834eea7&py_version=2.7
- Default Python version: 3.6 or 3
  - Because mypy uses Python 3 by default

**Comment by ymyzk** [comment]
This feature is implemented in #18 
Now, we can fetch a Gist using URL parameter! Example: https://play-mypy.ymyzk.com/?gist=f7fab5c5f47d260a5a3130a7461a4131
