### ISSUE TITLE
mypy "latest" is ambigious

### ISSUE THREAD

**Issue by DetachHead** [ymyzk/mypy-playground#147]
![image](https://user-images.githubusercontent.com/57028336/140467490-5095e867-d443-4b3f-aaf7-bdeea820d908.png)

we just had a lengthy debate in our team over what version of mypy "latest" refers to. it could mean the latest version from master (related: #139) or the latest released version.

i think it should show in brackets or something what version "latest" is actually referring to.

on typescript playground, clicking "Nightly", will show what exact version it resolved to:
![image](https://user-images.githubusercontent.com/57028336/140467750-17bc215a-b03e-4aec-a481-a0dad4532f7d.png)
![image](https://user-images.githubusercontent.com/57028336/140467820-9a5b9333-8ee2-473a-b584-47c578e5806a.png)

**Comment by ymyzk** [comment]
Thanks for the feedback! I updated mypy-play.net to use something like `latest (0.910)` instead of `latest`  as it's a one line configuration change.

JFYI, one way to double-check which mypy version is used is running mypy with `--verbose` flag: https://mypy-play.net/?mypy=latest&python=3.10&flags=verbose

**Comment by DetachHead** [comment]
awesome thanks
