### ISSUE TITLE
(🎁) add a favicon

### ISSUE THREAD

**Issue by KotlinIsland** [ymyzk/mypy-playground#227]
probably the mypy logo

**Comment by ymyzk** [comment]
I like the idea. It seems mypy doesn't set favicon yet.

- http://mypy-lang.org/
- https://mypy.readthedocs.io/en/stable/index.html

Although they have a nice logo for their documentation: https://mypy.readthedocs.io/en/stable/_static/mypy_light.svg

I'm not sure using the same logo as mypy itself is a good idea or not because it makes it difficult for users to distinguish mypy and mypy Playground in tabs or bookmarks. We may want to configure something else.

It may be okay to start with something very simple like this. It should be still better than nothing.

![android-chrome-192x192](https://user-images.githubusercontent.com/3383281/192098633-a3c15fdd-b0ed-4d28-a09d-98dbb6db0f0b.png)
