### ISSUE TITLE
Add `--enable-incomplete-feature` flag

### ISSUE THREAD

**Issue by martinkozle** [ymyzk/mypy-playground#465]
I wanted to test out the type hinting of the new kwargs TypedDict feature in Python 3.12, but I am getting the error:
```
error: "Unpack" support is experimental, use --enable-incomplete-feature=Unpack to enable  [misc]
```
Is this an option that you would consider adding?

**Comment by ymyzk** [comment]
Thanks for the suggestion, @martinkozle. I think this is a reasonable feature to add. At the same time, I'd like to avoid allowing users to give an arbitrary value for this option due to security concerns. Do you happen to know where we can find a list of options we can specify in `--enable-incomplete-feature`? I'd like to have an allow list with in mypy Playground.

**Comment by martinkozle** [comment]
I did some research and checked the mypy code directly and I found this constant defined here: https://github.com/python/mypy/blob/feb0fa75ca7f3abb1217d94f6ffb55994b9a31c8/mypy/options.py#L75C7-L75C7
Which is used to validate the `--enable-incomplete-feature` argument:
https://github.com/python/mypy/blob/feb0fa75ca7f3abb1217d94f6ffb55994b9a31c8/mypy/main.py#L1341C6-L1341C6
I hope that this is helpful.

**Comment by ymyzk** [comment]
@martinkozle, thanks for sharing your investigation result. It's really helpful to implement this feature. I've implemented this option in #505 and plan to update mypy-play.net soon. Please give it a try and share your thoughts.

**Comment by martinkozle** [comment]
I cloned it and ran it locally to test it with Unpack. Seems good, works as expected.

**Comment by ymyzk** [comment]
Nice, glad to hear that! I'm closing the issue now.
